channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.0.4
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.0
  - dataclasses==0.6
  - lightgbm==3.3.4
  - psutil==5.9.4
  - scikit-learn==1.2.0
  - typing-extensions==4.4.0
name: mlflow-env
