from pydantic import BaseModel
# 2. Class which describes Bank Notes measurements
class Credit_demand_columns(BaseModel):
    index:int
    SK_ID_CURR:int
    CODE_GENDER:int
    FLAG_OWN_CAR:int
    FLAG_OWN_REALTY:int
    CNT_CHILDREN:int
    AMT_INCOME_TOTAL:float
    AMT_CREDIT:float
    AMT_ANNUITY:float
    AMT_GOODS_PRICE:float
    REGION_POPULATION_RELATIVE:float
    DAYS_BIRTH:int
    DAYS_EMPLOYED:float
    DAYS_REGISTRATION:float
    DAYS_ID_PUBLISH:int
    OWN_CAR_AGE:float
    FLAG_MOBIL:int
    FLAG_EMP_PHONE:int
    FLAG_WORK_PHONE:int
    FLAG_CONT_MOBILE:int
    FLAG_PHONE:int
    FLAG_EMAIL:int
    CNT_FAM_MEMBERS:float
    REGION_RATING_CLIENT:int
    REGION_RATING_CLIENT_W_CITY:int
    HOUR_APPR_PROCESS_START:int
    REG_REGION_NOT_LIVE_REGION:int
    REG_REGION_NOT_WORK_REGION:int
    LIVE_REGION_NOT_WORK_REGION:int
    REG_CITY_NOT_LIVE_CITY:int
    REG_CITY_NOT_WORK_CITY:int
    LIVE_CITY_NOT_WORK_CITY:int
    EXT_SOURCE_1:float
    EXT_SOURCE_2:float
    EXT_SOURCE_3:float
    APARTMENTS_AVG:float
    BASEMENTAREA_AVG:float
    YEARS_BEGINEXPLUATATION_AVG:float
    YEARS_BUILD_AVG:float
    COMMONAREA_AVG:float
    ELEVATORS_AVG:float
    ENTRANCES_AVG:float
    FLOORSMAX_AVG:float
    FLOORSMIN_AVG:float
    LANDAREA_AVG:float
    LIVINGAPARTMENTS_AVG:float
    LIVINGAREA_AVG:float
    NONLIVINGAPARTMENTS_AVG:float
    NONLIVINGAREA_AVG:float
    APARTMENTS_MODE:float
    BASEMENTAREA_MODE:float
    YEARS_BEGINEXPLUATATION_MODE:float
    YEARS_BUILD_MODE:float
    COMMONAREA_MODE:float
    ELEVATORS_MODE:float
    ENTRANCES_MODE:float
    FLOORSMAX_MODE:float
    FLOORSMIN_MODE:float
    LANDAREA_MODE:float
    LIVINGAPARTMENTS_MODE:float
    LIVINGAREA_MODE:float
    NONLIVINGAPARTMENTS_MODE:float
    NONLIVINGAREA_MODE:float
    APARTMENTS_MEDI:float
    BASEMENTAREA_MEDI:float
    YEARS_BEGINEXPLUATATION_MEDI:float
    YEARS_BUILD_MEDI:float
    COMMONAREA_MEDI:float
    ELEVATORS_MEDI:float
    ENTRANCES_MEDI:float
    FLOORSMAX_MEDI:float
    FLOORSMIN_MEDI:float
    LANDAREA_MEDI:float
    LIVINGAPARTMENTS_MEDI:float
    LIVINGAREA_MEDI:float
    NONLIVINGAPARTMENTS_MEDI:float
    NONLIVINGAREA_MEDI:float
    TOTALAREA_MODE:float
    OBS_30_CNT_SOCIAL_CIRCLE:float
    DEF_30_CNT_SOCIAL_CIRCLE:float
    OBS_60_CNT_SOCIAL_CIRCLE:float
    DEF_60_CNT_SOCIAL_CIRCLE:float
    DAYS_LAST_PHONE_CHANGE:float
    FLAG_DOCUMENT_2:int
    FLAG_DOCUMENT_3:int
    FLAG_DOCUMENT_4:int
    FLAG_DOCUMENT_5:int
    FLAG_DOCUMENT_6:int
    FLAG_DOCUMENT_7:int
    FLAG_DOCUMENT_8:int
    FLAG_DOCUMENT_9:int
    FLAG_DOCUMENT_10:int
    FLAG_DOCUMENT_11:int
    FLAG_DOCUMENT_12:int
    FLAG_DOCUMENT_13:int
    FLAG_DOCUMENT_14:int
    FLAG_DOCUMENT_15:int
    FLAG_DOCUMENT_16:int
    FLAG_DOCUMENT_17:int
    FLAG_DOCUMENT_18:int
    FLAG_DOCUMENT_19:int
    FLAG_DOCUMENT_20:int
    FLAG_DOCUMENT_21:int
    AMT_REQ_CREDIT_BUREAU_HOUR:float
    AMT_REQ_CREDIT_BUREAU_DAY:float
    AMT_REQ_CREDIT_BUREAU_WEEK:float
    AMT_REQ_CREDIT_BUREAU_MON:float
    AMT_REQ_CREDIT_BUREAU_QRT:float
    AMT_REQ_CREDIT_BUREAU_YEAR:float
    NAME_CONTRACT_TYPE_Cash_loans:int
    NAME_CONTRACT_TYPE_Revolving_loans:int
    NAME_CONTRACT_TYPE_nan:int
    NAME_TYPE_SUITE_Children:int
    NAME_TYPE_SUITE_Family:int
    NAME_TYPE_SUITE_Group_of_people:int
    NAME_TYPE_SUITE_Other_A:int
    NAME_TYPE_SUITE_Other_B:int
    NAME_TYPE_SUITE_Spouse_partner:int
    NAME_TYPE_SUITE_Unaccompanied:int
    NAME_TYPE_SUITE_nan:int
    NAME_INCOME_TYPE_Businessman:int
    NAME_INCOME_TYPE_Commercial_associate:int
    NAME_INCOME_TYPE_Maternity_leave:int
    NAME_INCOME_TYPE_Pensioner:int
    NAME_INCOME_TYPE_State_servant:int
    NAME_INCOME_TYPE_Student:int
    NAME_INCOME_TYPE_Unemployed:int
    NAME_INCOME_TYPE_Working:int
    NAME_INCOME_TYPE_nan:int
    NAME_EDUCATION_TYPE_Academic_degree:int
    NAME_EDUCATION_TYPE_Higher_education:int
    NAME_EDUCATION_TYPE_Incomplete_higher:int
    NAME_EDUCATION_TYPE_Lower_secondary:int
    NAME_EDUCATION_TYPE_Secondary_secondary_special:int
    NAME_EDUCATION_TYPE_nan:int
    NAME_FAMILY_STATUS_Civil_marriage:int
    NAME_FAMILY_STATUS_Married:int
    NAME_FAMILY_STATUS_Separated:int
    NAME_FAMILY_STATUS_Single_not_married:int
    NAME_FAMILY_STATUS_Unknown:int
    NAME_FAMILY_STATUS_Widow:int
    NAME_FAMILY_STATUS_nan:int
    NAME_HOUSING_TYPE_Co_op_apartment:int
    NAME_HOUSING_TYPE_House_apartment:int
    NAME_HOUSING_TYPE_Municipal_apartment:int
    NAME_HOUSING_TYPE_Office_apartment:int
    NAME_HOUSING_TYPE_Rented_apartment:int
    NAME_HOUSING_TYPE_With_parents:int
    NAME_HOUSING_TYPE_nan:int
    OCCUPATION_TYPE_Accountants:int
    OCCUPATION_TYPE_Cleaning_staff:int
    OCCUPATION_TYPE_Cooking_staff:int
    OCCUPATION_TYPE_Core_staff:int
    OCCUPATION_TYPE_Drivers:int
    OCCUPATION_TYPE_HR_staff:int
    OCCUPATION_TYPE_High_skill_tech_staff:int
    OCCUPATION_TYPE_IT_staff:int
    OCCUPATION_TYPE_Laborers:int
    OCCUPATION_TYPE_Low_skill_Laborers:int
    OCCUPATION_TYPE_Managers:int
    OCCUPATION_TYPE_Medicine_staff:int
    OCCUPATION_TYPE_Private_service_staff:int
    OCCUPATION_TYPE_Realty_agents:int
    OCCUPATION_TYPE_Sales_staff:int
    OCCUPATION_TYPE_Secretaries:int
    OCCUPATION_TYPE_Security_staff:int
    OCCUPATION_TYPE_Waiters_barmen_staff:int
    OCCUPATION_TYPE_nan:int
    WEEKDAY_APPR_PROCESS_START_FRIDAY:int
    WEEKDAY_APPR_PROCESS_START_MONDAY:int
    WEEKDAY_APPR_PROCESS_START_SATURDAY:int
    WEEKDAY_APPR_PROCESS_START_SUNDAY:int
    WEEKDAY_APPR_PROCESS_START_THURSDAY:int
    WEEKDAY_APPR_PROCESS_START_TUESDAY:int
    WEEKDAY_APPR_PROCESS_START_WEDNESDAY:int
    WEEKDAY_APPR_PROCESS_START_nan:int
    ORGANIZATION_TYPE_Advertising:int
    ORGANIZATION_TYPE_Agriculture:int
    ORGANIZATION_TYPE_Bank:int
    ORGANIZATION_TYPE_Business_Entity_Type_1:int
    ORGANIZATION_TYPE_Business_Entity_Type_2:int
    ORGANIZATION_TYPE_Business_Entity_Type_3:int
    ORGANIZATION_TYPE_Cleaning:int
    ORGANIZATION_TYPE_Construction:int
    ORGANIZATION_TYPE_Culture:int
    ORGANIZATION_TYPE_Electricity:int
    ORGANIZATION_TYPE_Emergency:int
    ORGANIZATION_TYPE_Government:int
    ORGANIZATION_TYPE_Hotel:int
    ORGANIZATION_TYPE_Housing:int
    ORGANIZATION_TYPE_Industry_type_1:int
    ORGANIZATION_TYPE_Industry_type_10:int
    ORGANIZATION_TYPE_Industry_type_11:int
    ORGANIZATION_TYPE_Industry_type_12:int
    ORGANIZATION_TYPE_Industry_type_13:int
    ORGANIZATION_TYPE_Industry_type_2:int
    ORGANIZATION_TYPE_Industry_type_3:int
    ORGANIZATION_TYPE_Industry_type_4:int
    ORGANIZATION_TYPE_Industry_type_5:int
    ORGANIZATION_TYPE_Industry_type_6:int
    ORGANIZATION_TYPE_Industry_type_7:int
    ORGANIZATION_TYPE_Industry_type_8:int
    ORGANIZATION_TYPE_Industry_type_9:int
    ORGANIZATION_TYPE_Insurance:int
    ORGANIZATION_TYPE_Kindergarten:int
    ORGANIZATION_TYPE_Legal_Services:int
    ORGANIZATION_TYPE_Medicine:int
    ORGANIZATION_TYPE_Military:int
    ORGANIZATION_TYPE_Mobile:int
    ORGANIZATION_TYPE_Other:int
    ORGANIZATION_TYPE_Police:int
    ORGANIZATION_TYPE_Postal:int
    ORGANIZATION_TYPE_Realtor:int
    ORGANIZATION_TYPE_Religion:int
    ORGANIZATION_TYPE_Restaurant:int
    ORGANIZATION_TYPE_School:int
    ORGANIZATION_TYPE_Security:int
    ORGANIZATION_TYPE_Security_Ministries:int
    ORGANIZATION_TYPE_Self_employed:int
    ORGANIZATION_TYPE_Services:int
    ORGANIZATION_TYPE_Telecom:int
    ORGANIZATION_TYPE_Trade_type_1:int
    ORGANIZATION_TYPE_Trade_type_2:int
    ORGANIZATION_TYPE_Trade_type_3:int
    ORGANIZATION_TYPE_Trade_type_4:int
    ORGANIZATION_TYPE_Trade_type_5:int
    ORGANIZATION_TYPE_Trade_type_6:int
    ORGANIZATION_TYPE_Trade_type_7:int
    ORGANIZATION_TYPE_Transport_type_1:int
    ORGANIZATION_TYPE_Transport_type_2:int
    ORGANIZATION_TYPE_Transport_type_3:int
    ORGANIZATION_TYPE_Transport_type_4:int
    ORGANIZATION_TYPE_University:int
    ORGANIZATION_TYPE_XNA:int
    ORGANIZATION_TYPE_nan:int
    FONDKAPREMONT_MODE_not_specified:int
    FONDKAPREMONT_MODE_org_spec_account:int
    FONDKAPREMONT_MODE_reg_oper_account:int
    FONDKAPREMONT_MODE_reg_oper_spec_account:int
    FONDKAPREMONT_MODE_nan:int
    HOUSETYPE_MODE_block_of_flats:int
    HOUSETYPE_MODE_specific_housing:int
    HOUSETYPE_MODE_terraced_house:int
    HOUSETYPE_MODE_nan:int
    WALLSMATERIAL_MODE_Block:int
    WALLSMATERIAL_MODE_Mixed:int
    WALLSMATERIAL_MODE_Monolithic:int
    WALLSMATERIAL_MODE_Others:int
    WALLSMATERIAL_MODE_Panel:int
    WALLSMATERIAL_MODE_Stone_brick:int
    WALLSMATERIAL_MODE_Wooden:int
    WALLSMATERIAL_MODE_nan:int
    EMERGENCYSTATE_MODE_No:int
    EMERGENCYSTATE_MODE_Yes:int
    EMERGENCYSTATE_MODE_nan:int
    DAYS_EMPLOYED_PERC:float
    INCOME_CREDIT_PERC:float
    INCOME_PER_PERSON:float
    ANNUITY_INCOME_PERC:float
    PAYMENT_RATE:float

